cuotas/urls.py
from .views import registrar_cuota_social, registrar_cuota_extra
from django.urls import path

app_name = 'cuotas'
urlpatterns = [
    path('registrar_cuota_social/', registrar_cuota_social, name='registrar_cuota_social'),
    path('registrar_cuota_extra/', registrar_cuota_extra, name='registrar_cuota_extra'),
]

sistWebElMirador/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import myHomeView

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', myHomeView, name='home'),
    path('socios/', include('socios.urls')),
    path('terrenos/', include('terrenos.urls')),
    path('cuotas/', include('cuotas.urls')),
]

socios/urls.py
from socios.views import registrar_socio, iniciar_sesion, cerrar_sesion
from django.urls import path

app_name = 'socios'
urlpatterns = [
    path('registrar/', registrar_socio, name='registrar_socio'),
    path('iniciar_sesion/', iniciar_sesion, name="iniciar_sesion"),
    path('cerrar_sesion/', cerrar_sesion, name='cerrar_sesion'),
]

terrenos/urls.py
from .views import registrar_terreno
from django.urls import path

app_name = 'terrenos'
urlpatterns = [
    path('registrar/', registrar_terreno, name='registrar_terreno'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %}Asoc. El Mirador Zn C{% endblock %}</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
  integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  <link rel="shortcut icon" href="{% static '/favicon.ico' %}" />
</head>
<body>
  <nav class="navbar navbar-expand-lg bg-dark navbar-dark">
    <div class="container">
      <a class="navbar-brand" href="{% url 'home' %}">El Mirador Zona 'C'</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav  ms-auto">
          
          {% if user.is_authenticated %}
          {% if user.is_superuser %}
          <li class="nav-item">
            <a class="nav-link" href="/admin/">Admin</a>
          </li>
          {% endif %}
          {% if user.is_staff %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Socios
            </a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="{% url 'socios:registrar_socio' %}">Registrar</a></li>
              <li><a class="dropdown-item" href="#">Visualizar</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="#">Something else here</a></li>
            </ul>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'terrenos:registrar_terreno' %}">Terrenos</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Cuotas
            </a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="{% url 'cuotas:registrar_cuota_social' %}">Registrar Cuota Social</a></li>
              <li><a class="dropdown-item" href="{% url 'cuotas:registrar_cuota_extra' %}">Registrar Cuota Extraordinaria</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="#">Something else here</a></li>
            </ul>
          </li>
          {% endif %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'socios:cerrar_sesion' %}">Cerrar Sesión</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'socios:iniciar_sesion' %}">Iniciar Sesión</a>
          </li>
          {% endif %}
          <li class="nav-item">
            <a class="nav-link disabled">Disabled</a>
          </li>
        </ul>
        
      </div>
    </div>
  </nav>
  <div class="container">
    <h5>Bienvenido {% if user.is_authenticated %} 
      {{user.nombres}} {{user.primer_apellido}} {{user.segundo_apellido}},
    {% endif %} al</h5>
    
    
  

    {% block content %} 
    {% endblock %}
  </div>
  <!-- Footer -->
  <br>
<footer class="text-center text-lg-start bg-dark text-muted">
  
  <!-- Section: Links  -->
  <section class="py-1">
    <div class="container text-center text-md-start mt-5">
      <!-- Grid row -->
      <div class="row mt-3">
        <!-- Grid column -->
        <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
          <!-- Content -->
          <h6 class="text-uppercase fw-bold mb-4">
            <i class="fas fa-gem me-3"></i>El Mirador Zona C
          </h6>
          <p>
            A por la titulación.
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">
            Products
          </h6>
          <p>
            <a href="#!" class="text-reset">Angular</a>
          </p>
          <p>
            <a href="#!" class="text-reset">React</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Vue</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Laravel</a>
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">
            Useful links
          </h6>
          <p>
            <a href="#!" class="text-reset">Pricing</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Settings</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Orders</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Help</a>
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">Contacto</h6>
          <p><i class="fas fa-home me-3"></i> Mz 'I' Lt 11</p>
          <p>
            <i class="fas fa-envelope me-3"></i>
            anthony.rivas.dev@gmail.com
          </p>
          <p><i class="fas fa-phone me-3"></i> + 51 930 274 772</p>
        </div>
        <!-- Grid column -->
      </div>
      <!-- Grid row -->
    </div>
  </section>
  <!-- Section: Links  -->

  <!-- Copyright -->
  <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
    Copyright:
    <a class="text-reset fw-bold" 
    href="https://www.linkedin.com/in/anthonyrivaschire/">
    Anthony J. Rivas Chire</a>
    © 2023 Todos los Derechos Reservados
  </div>
  <!-- Copyright -->
</footer>
<!-- Footer -->
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
  integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js"
  integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block title %}El Mirador Zona C{% endblock %}

{% block content %}
    <div class="container text-center py-5">
        <strong class="display-1">Sistema de la Asoc. de Vivienda "El Mirador Zona C"</strong>
    </div>
{% endblock %}